#!/usr/bin/env node
// skillWriter.js — Write/delete auto-generated skill files in .claude/skills/
// Handles methodology-level rules that graduate into standalone skill files.
// Zero npm dependencies — uses only Node.js built-ins.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SKILLS_DIR = '.claude/skills';
const SKILL_PREFIX = 'auto-';
const HASH_MARKER = 'claude-evolve:auto-skill';

// ===================== Slug generation =====================

/**
 * Generate a URL-safe slug from rule keywords or content.
 * @param {Object} rule - Rule object with keywords and/or content
 * @returns {string} Slug like "bq-analysis-workflow"
 */
function generateSlug(rule) {
  // Prefer keywords array, fall back to extracting from content
  const words = (rule.keywords && rule.keywords.length > 0)
    ? rule.keywords.slice(0, 5)
    : (rule.content || '').toLowerCase()
        .replace(/[^a-z0-9\s-]/g, ' ')
        .split(/\s+/)
        .filter(w => w.length > 2)
        .slice(0, 5);

  const slug = words
    .map(w => w.toLowerCase().replace(/[^a-z0-9]/g, ''))
    .filter(Boolean)
    .join('-');

  return slug || ('skill-' + (rule.id || Date.now().toString(36)));
}

// ===================== Hash computation =====================

/**
 * Compute SHA-256 hash of content, excluding the hash line itself.
 * @param {string} content - Full file content
 * @returns {string} Hex hash
 */
function computeHash(content) {
  // Remove the first line (which contains the hash marker) before hashing
  const lines = content.split('\n');
  const bodyLines = [];
  let skippedMarker = false;
  for (const line of lines) {
    if (!skippedMarker && line.includes(HASH_MARKER)) {
      skippedMarker = true;
      continue;
    }
    bodyLines.push(line);
  }
  const body = bodyLines.join('\n');
  return crypto.createHash('sha256').update(body, 'utf8').digest('hex');
}

/**
 * Extract stored hash from file content.
 * @param {string} content - File content
 * @returns {string|null} Stored hash or null
 */
function extractStoredHash(content) {
  const match = content.match(/claude-evolve:auto-skill\s+hash=([a-f0-9]+)/);
  return match ? match[1] : null;
}

// ===================== Skill file path =====================

/**
 * Returns the path where this rule's skill file would be/is.
 * @param {string} projectPath - Project root path
 * @param {Object} rule - Rule object
 * @returns {string} Absolute path to skill file
 */
function findSkillFile(projectPath, rule) {
  const slug = generateSlug(rule);
  return path.join(projectPath, SKILLS_DIR, SKILL_PREFIX + slug + '.md');
}

// ===================== Build skill content =====================

/**
 * Build the markdown content for a skill file from a GROUP of related rules.
 * Merges related rules into a coherent methodology skill with proper Claude Code format.
 *
 * @param {Object} primaryRule - The main rule (highest score or first in group)
 * @param {Array} relatedRules - Other rules in the same methodology group
 * @param {string} slug - Generated slug
 * @param {string} projectType - Project type (e.g., 'analysis', 'backend')
 * @returns {string} Skill file body (everything except the hash marker line)
 */
function buildSkillBody(primaryRule, relatedRules, slug, projectType) {
  const allRules = [primaryRule, ...(relatedRules || [])];
  const allKeywords = [...new Set(allRules.flatMap(r => r.keywords || []))];

  // Build a one-line description from the combined keywords
  const domainTerms = allKeywords.filter(k => k.length > 2).slice(0, 4).join(', ');
  const description = `${domainTerms} workflow — auto-learned from ${allRules.length} observed patterns`;

  // Build trigger phrases from keywords
  const triggers = allKeywords
    .filter(k => k.length > 2 && !/^[A-Z]/.test(k))
    .slice(0, 5);

  const lines = [
    '---',
    `name: ${SKILL_PREFIX}${slug}`,
    `description: |`,
    `  ${description}.`,
    `  Auto-generated by claude-evolve from observed session patterns.`,
    `  Invoke when working on ${projectType || 'this type of'} tasks.`,
  ];

  // Add triggers if we have meaningful ones
  if (triggers.length >= 2) {
    lines.push('triggers:');
    for (const t of triggers) {
      lines.push(`  - ${t}`);
    }
  }

  lines.push('---');
  lines.push('');

  // Methodology description
  lines.push(`# ${domainTerms} Methodology`);
  lines.push('');
  lines.push(`Auto-learned from ${primaryRule.sessions_evaluated || '?'} sessions of ${projectType || 'project'} work.`);
  lines.push(`This skill encodes patterns that were consistently followed and proved useful over time.`);
  lines.push('');

  // Steps: each rule becomes a numbered step
  lines.push('## Steps');
  lines.push('');
  allRules.forEach((rule, i) => {
    const content = (rule.content || '').trim().replace(/^[-*]\s*/, '');
    lines.push(`${i + 1}. ${content}`);
  });
  lines.push('');

  // Source information
  lines.push('## About this skill');
  lines.push('');
  lines.push('This skill was automatically generated by [claude-evolve](https://github.com/jack60810/claude-evolve).');
  lines.push(`It observed ${primaryRule.sessions_evaluated || '?'} sessions and found these ${allRules.length} patterns consistently applied.`);
  lines.push('Rules with score < 3 will be automatically demoted, and this skill file will be deleted.');
  lines.push('');
  lines.push('You can edit this file freely. claude-evolve will detect your edits (via content hash) and stop overwriting.');

  return lines.join('\n') + '\n';
}

// ===================== Write skill =====================

/**
 * Write a SINGLE skill file for a METHODOLOGY GROUP of related rules.
 * Uses Claude Code (via llmBrain) to generate the skill content — Claude natively
 * understands the skill format and produces much better output than templates.
 *
 * @param {string} projectPath - Project root path
 * @param {Object} primaryRule - The primary rule in the group
 * @param {Array} relatedRules - Other rules in the same methodology group
 * @param {string} projectType - Project type (e.g., 'analysis')
 * @param {Array} [memories] - User memories for thinking pattern inference
 * @param {Array} [sessionNarratives] - Session narratives for context
 * @returns {{ written: boolean, path: string, reason?: string }}
 */
function writeSkill(projectPath, primaryRule, relatedRules, projectType, memories, sessionNarratives) {
  const allRules = [primaryRule, ...(relatedRules || [])];
  const combinedKeywords = [...new Set(allRules.flatMap(r => r.keywords || []))];
  const fallbackSlug = generateSlug({ keywords: combinedKeywords, id: primaryRule.id });

  // Ensure directory exists
  const skillDir = path.join(projectPath, SKILLS_DIR);
  fs.mkdirSync(skillDir, { recursive: true });

  // Call Claude Code to generate the skill content (with memories for thinking-pattern inference)
  const llmBrain = require('./llmBrain');
  const result = llmBrain.generateSkillContent(allRules, projectType, fallbackSlug, memories, sessionNarratives);

  // Fix 5: Extract name from LLM-generated content for a better slug
  let slug = fallbackSlug;
  if (result && result.content) {
    const nameMatch = result.content.match(/name:\s*"?auto-([^"\n]+)"?/);
    if (nameMatch) slug = nameMatch[1].trim().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
  }

  const skillPath = path.join(skillDir, SKILL_PREFIX + slug + '.md');

  // Check if file already exists and user has edited it
  // Also check old slug path (in case LLM changed the name)
  const oldPath = path.join(skillDir, SKILL_PREFIX + fallbackSlug + '.md');
  for (const checkPath of [skillPath, oldPath]) {
    if (fs.existsSync(checkPath)) {
      const existing = fs.readFileSync(checkPath, 'utf8');
      const storedHash = extractStoredHash(existing);
      if (storedHash) {
        const existingBody = existing.split('\n').slice(1).join('\n');
        const existingBodyHash = crypto.createHash('sha256').update(existingBody, 'utf8').digest('hex');
        if (storedHash !== existingBodyHash) {
          return { written: false, path: checkPath, reason: 'user-edited' };
        }
      }
      // Clean up old slug file if name changed
      if (checkPath === oldPath && checkPath !== skillPath) {
        try { fs.unlinkSync(oldPath); } catch {}
      }
      break;
    }
  }

  if (!result || !result.content) {
    // LLM failed — fall back to basic template
    const body = buildSkillBody(primaryRule, relatedRules, slug, projectType);
    const hash = crypto.createHash('sha256').update(body, 'utf8').digest('hex');
    const created = primaryRule.created || new Date().toISOString().slice(0, 10);
    const fullContent = `<!-- ${HASH_MARKER} hash=${hash} project-type=${projectType || 'unknown'} created=${created} -->\n${body}`;
    const tmp = skillPath + '.tmp';
    fs.writeFileSync(tmp, fullContent, 'utf8');
    fs.renameSync(tmp, skillPath);
    return { written: true, path: skillPath, reason: 'template-fallback' };
  }

  // Add hash marker for user-edit detection
  const body = result.content;
  const hash = crypto.createHash('sha256').update(body, 'utf8').digest('hex');
  const created = primaryRule.created || new Date().toISOString().slice(0, 10);
  const fullContent = `<!-- ${HASH_MARKER} hash=${hash} project-type=${projectType || 'unknown'} created=${created} -->\n${body}`;

  // Atomic write
  const tmp = skillPath + '.tmp';
  fs.writeFileSync(tmp, fullContent, 'utf8');
  fs.renameSync(tmp, skillPath);

  return { written: true, path: skillPath };
}

// ===================== Delete skill =====================

/**
 * Delete the skill file for a rule.
 * No error if file is already gone.
 *
 * @param {string} projectPath - Project root path
 * @param {Object} rule - Rule object with skill_path or keywords for lookup
 * @returns {{ deleted: boolean, path: string }}
 */
function deleteSkill(projectPath, rule) {
  const skillPath = rule.skill_path || findSkillFile(projectPath, rule);

  if (fs.existsSync(skillPath)) {
    fs.unlinkSync(skillPath);
    const msg = `[skillWriter] Deleted skill file: ${skillPath}`;
    if (typeof console !== 'undefined') console.log(msg);
    return { deleted: true, path: skillPath };
  }

  return { deleted: false, path: skillPath };
}

module.exports = {
  writeSkill,
  deleteSkill,
  findSkillFile,
  // Exported for testing
  generateSlug,
  computeHash,
  extractStoredHash,
  buildSkillBody,
};
